### PR TITLE
Remove alvaw32.dll

### PR DESCRIPTION
**Pull request by dkager**
This library is no longer needed with the introduction of the native ALVA BC6 driver in NVDA 2018.1.

### CODE REVIEW

**Comment by LeonarddeR** [comment]
Could you also remove HanSoneConnect.dll and SyncBraille.dll within the scope of this pr?

**Comment by dkager** [comment]
> Could you also remove HanSoneConnect.dll and SyncBraille.dll within the scope of this pr?

What is the motivation?

**Comment by LeonarddeR** [comment]
They are also no longer in use since we have a native Hims driver.

**Comment by LeonarddeR** [comment]
cc @Michaeldcurran

**Comment by LeonarddeR** [comment]
It looks like this has already been addressed. @dkager: I think you can close this.

**Pull request closed without merging**
