### PR TITLE
Add m4

### PR DESCRIPTION
**Pull request by LeonarddeR**
Bundle m4 with miscdeps to compile liblouis tables containing macros. See also https://github.com/nvaccess/nvda/pull/16652
cc @codeofdusk

### CODE REVIEW

**Comment by codeofdusk** [comment]
@LeonarddeR Could you please also create a PR against my `liblouis-3.30` branch to update the sconstruct with the necessary commands to build the new tables?

**Comment by LeonarddeR** [comment]
Yes, I'll try to do that tomorrow.

**Comment by LeonarddeR** [comment]
@seanbudd This appears to be working great, so if you could merge this in, @codeofdusk can finish https://github.com/nvaccess/nvda/pull/16652
Note that m4 is gpl v3, I don't think that's problematic? We clearly list the source in the readme.

**Review by seanbudd — APPROVED** [review]
I've checked the file checksums and these appear to be correct

**Review by seanbudd — APPROVED** [review]
I've checked the file checksums and these appear to be correct

**Pull request merged**
