### PR TITLE
Upgrade NSIS to version 3.05 to address potential security issues.

### PR DESCRIPTION
**Pull request by dpy013**
hi
#9134 
Upgrade NSIS 2.51 to version 3.05 to address potential security issues.
thanks

### CODE REVIEW

**Comment by dpy013** [comment]
cc @michaelDCurran and
@feerrenrut

**Comment by LeonarddeR** [comment]
Could you provide details on how you tested this?

**Comment by dpy013** [comment]
> Could you provide details on how you tested this?
hi leonardder
The following is the test method:
First install the NVDA compilation environment, then clone the NVDA source code, then replace the NSIS version dimension 3.05 of miscDeps / tools, and finally run scons launcher version = test1 to compile and test.
thanks

**Comment by feerrenrut** [comment]
@dingpengyu 
Could you please expand on the "test" part. Which OS versions have you tested on? Have you tested running from launcher / create portable / full install? What about the various other options for the install? Command line arguments to the launcher. etc?

This testing work could be distributed to community volunteers, however first you (or whoever wants to take ownership of this work) will have to create a test plan.

**Comment by LeonarddeR** [comment]
Be also sure to test the uninstaller and consider that we're using a [NSIS UAC plug-in](https://nsis.sourceforge.io/UAC_plug-in), version 0.2.4, ansi. This plugin is deprecated, so we should find out whether or not we should still use it.

I also prefer trying to switch to [unicode mode](https://nsis.sourceforge.io/Reference/Unicode) while at it.

Without these things, I don't think a switch to a newer NSIS is very beneficial to us.

**Comment by dpy013** [comment]
hello
 i am ready to close this pull_request.
nsis3.05 requires careful consideration to make the switch, and I will continue to study this issue.
Thanks everyone for your comments

**Pull request closed without merging**
