### PR TITLE
Update ISimpleDOM and gettext

### PR DESCRIPTION
**Pull request by OzancanKaratas**
ISimpleDOM has been updated from gecko-dev repository.

gettext has been updated to version 0.21 from the official GNU website. Added 32-bit static binaries.

### CODE REVIEW

**Comment by OzancanKaratas** [comment]
@seanbudd, @feerrenrut or @michaelDCurran: I don't know if there is any significant change here. But I wanted to apply the update.

**Comment by seanbudd** [comment]
Is there a related change log file? Where did you update this from?

**Comment by OzancanKaratas** [comment]
I updated this from [here](https://chromium.googlesource.com/chromium/src/+/HEAD/third_party/isimpledom).

**Comment by seanbudd** [comment]
This appears to diverge from the Mozilla source definitions.

Correct me if I'm wrong, but I believe this is the correct source of truth: https://github.com/mozilla/gecko-dev/tree/master/accessible/interfaces/msaa

The diff in this PR appears to the same as the diff between the files in the Chromium repo you linked, and the Mozilla repo.

**Comment by OzancanKaratas** [comment]
I don't quite understand what you mean. But the source in the Chromium repository is more up to date. Please compare the files in the Mozilla and Chromium repositories.

**Comment by OzancanKaratas** [comment]
You can review. If the ones in the Chromium repository are better, I can revert the latest commit.

**Comment by seanbudd** [comment]
How do we know which ones are better?
I don't really understand why we should merge either set of changes.

**Comment by OzancanKaratas** [comment]
I used the files from Mozilla's repository instead of the files from the first commit because the source you provided is correct. It seems more logical to use the latest files from the official source instead of thinking about which one is better.

**Comment by seanbudd** [comment]
Hi @OzancanKaratas - I am closing this as the changes are stale, and don't appear to be meaningful. I am also concerned about the tool binaries being removed.

If there have been new updates since the last review, feel free to re-open a PR integrating the latest changes.

**Pull request closed without merging**
