### PR TITLE
Remove Handy Tech COM server

### PR DESCRIPTION
**Pull request by bramd**
Required for PR nvaccess/nvda#7590 (related to issue nvaccess/nvda#7458)

### CODE REVIEW

**Comment by LeonarddeR** [comment]
@MichaelDCurran: Note that this is also part of nvaccess/nvda#7590

**Comment by LeonarddeR** [comment]
I think this can be closed, it is better to supersede this with a more broad removal of unused dlls.

**Comment by michaelDCurran** [comment]
So to be clear, is it okay now to remove the Handy Tech  stuff from 
miscDeps? I believe it was kept for use in an add-on or something?

**Comment by LeonarddeR** [comment]
There is a handytech classic driver on their ftp, but I don't know whether that's ready to use yet.
CC @FelixGruetzmacher

**Comment by FelixGruetzmacher** [comment]
The classic driver is just a Python wrapper for the com server. Feel free to remove the com server from NVDA---we'll provide a setup for the most recent version in the next few days.

**Comment by LeonarddeR** [comment]
@michaeldcurran: this can be removed for nvaccess/nvda#9605

**Review by michaelDCurran — APPROVED** [review]

**Pull request merged**
