### PR TITLE
Upgrade xgettext to 0.20.2

### PR DESCRIPTION
**Pull request by dpy013**
hello
gettext 0.20.2 was officially released six days ago.
[Here is the change log for this version](http://savannah.gnu.org/forum/forum.php?forum_id=9716)
Update gettext0.18.1.0 to 0.20.2 from [mlocati gettext-iconv-windows](https://github.com/mlocati/gettext-iconv-windows)
thanks

### CODE REVIEW

**Comment by dingpengyu** [comment]
@michaelDCurran Any suggestions for this pr?

**Comment by dingpengyu** [comment]
Request a review
@feerrenrut

**Comment by LeonarddeR** [comment]
Could you elaborate on what testing you've done with this pr?

**Comment by dpy013** [comment]
> Could you elaborate on what testing you've done with this pr?

I used xgettext 0.20.2 to build the NVDA in the local environment, and the translation was normal. The .mo was generated from the .po.

**Comment by dpy013** [comment]
test environment
Visual Studio 2019  version16.5.4
python 3.7.7
scons 3.1.2
windows10-2004 19041.207
virtualenv 20.0.20

**Comment by feerrenrut** [comment]
It would be good if there was a rundown of the changes that are relevant to NVDA. Here is the full change log document: https://git.savannah.gnu.org/gitweb/?p=gettext.git;a=blob_plain;f=NEWS;hb=HEAD

**Comment by dpy013** [comment]
> It would be good if there was a rundown of the changes that are relevant to NVDA. Here is the full change log document: https://git.savannah.gnu.org/gitweb/?p=gettext.git;a=blob_plain;f=NEWS;hb=HEAD

gettext 0.20.2 Mainly supports UTF8 This is a better place.

**Comment by dingpengyu** [comment]
#11142

**Comment by dingpengyu** [comment]
> It would be good if there was a rundown of the changes that are relevant to NVDA. Here is the full change log document: https://git.savannah.gnu.org/gitweb/?p=gettext.git;a=blob_plain;f=NEWS;hb=HEAD

What else needs to be added to the current pr?

**Comment by LeonarddeR** [comment]
@dingpengyu If there is more work needed, you will be informed when time allows. Note that we aren't suffering from issues for gettext currently, and therefore this pr might not be acted upon before preparations start for NVDA 2020.3.

**Comment by dingpengyu** [comment]
> Request a review
> @feerrenrut
and
@michaelDCurran 
thanks

**Comment by LeonarddeR** [comment]
@dingpengyu please pay attention to the following request.

> @dingpengyu If there is more work needed, you will be informed when time allows. Note that we aren't suffering from issues for gettext currently, and therefore this pr might not be acted upon before preparations start for NVDA 2020.3.

Could you please refrain from additional requests for review like this?

**Comment by dpy013** [comment]
I marked this pull request as draft, If there is a maintainer interested in maintaining this pr, they can do so, I've been very busy lately and haven't had much time to maintain this pr.
In reply to leonardder, why am I in a hurry to merge, because I personally do not like to drag things out, strive for It's my style to do it all at once.
Thanks for the reminder.

**Pull request closed without merging**
